#!/bin/python3
#taking import or library
import os,sys
import time
import requests
#functions for letter work
os.system("clear")
def banner():
    os.system("bash Banner.sh")
def menu(banner,backtomenu):
    banner()
    menu="""
    [01]PBF (Profile Brute Force)
    [02]Brute Force (Simple password attack)
    """
    print("\033[1;31m"+menu)
    backtomenu()
def backtomenu():
    backtomenu="""
    [88] Update
    [99] Back to main menu
    [00] Exit
    """
    print(backtomenu)
def PBF(banner,backtomenu):
    banner()
    #Thare user give info of victim and program send it on a file.
    fn=input("Enter Victim First Name:")
    ln=input("Enter Victim Last Name:")
    tn=input("Enter Victim 3RD Name:")
    #Creating a file with victm first name
    p=open(fn+".txt","a")
    print("Passlist are created on PyPass as",fn+".txt")
    #password are making on there
    p.write(fn+"123" "\n")
    p.write(fn+"1234" "\n")
    p.write(fn+"12345" "\n")
    p.write(fn+"777" "\n")
    p.write(fn+"768" "\n")
    p.write(fn+"111" "\n")
    p.write(fn+"222" "\n")
    p.write(fn+"333" "\n")
    p.write(fn+"444" "\n")
    p.write(fn+"555" "\n")
    p.write(fn+"666" "\n")
    p.write(fn+"888" "\n")
    p.write(fn+"999" "\n")
    p.write(fn+"000" "\n")
    p.write(fn+"567" "\n")
    p.write(fn+"678" "\n")
    p.write(fn+"789" "\n")
    p.write(fn+"890" "\n")
    p.write(fn+"345" "\n")
    p.write(fn+"1111" "\n")
    p.write(fn+"2222" "\n")
    p.write(ln+"123" "\n")
    p.write(ln+"1234" "\n")
    p.write(ln+"12345" "\n")
    p.write(ln+"111""\n")
    p.write(ln+"000" "\n")
    p.write(ln+"222" "\n")
    p.write(ln+"333" "\n")
    p.write(ln+"444" "\n")
    p.write(ln+"555" "\n")
    p.write(ln+"666" "\n")
    p.write(ln+"777" "\n")
    p.write(ln+"888" "\n")
    p.write(ln+"999" "\n")
    p.write(ln+"1111" "\n")
    p.write(ln+"2222" "\n")
    p.write(ln+"3333" "\n")
    p.write(ln+"4444" "\n")
    p.write(ln+"5555" "\n")
    p.write(ln+"6666" "\n")
    p.write(ln+"7777" "\n")
    p.write(ln+"8888" "\n")
    p.write(ln+"9999" "\n")
    p.write(ln+"0000" "\n")
    p.write(tn+"123" "\n")
    p.write(tn+"000" "\n")
    p.write(tn+"786" "\n")
    p.write(tn+"777" "\n")
    p.write(tn+"999" "\n")
    p.write(tn+"888" "\n")
    p.write(tn+"666" "\n")
    p.write(tn+"555" "\n")
    p.write(tn+"444" "\n")
    p.write(tn+"333" "\n")
    p.write(tn+"222" "\n")
    p.write(tn+ln+fn+ "\n")
    p.write(ln+tn+fn+ "\n")
    p.write(fn+ln+tn+ "\n")
    p.write(ln+fn+tn+ "\n")
    p.write(tn+fn+ln+"123" "\n")
    p.write(tn+fn+ln+"1234" "\n")
def BF(banner,backtomenu):
    banner()
    os.system("cd FB && python3 fb.py")
    time.sleep(3)
    os.system("python3 DORKLIN")
menu(banner,backtomenu)
choice=input("\033[1;31mEnter youre choice:")
if choice == "1" or choice == "01":
    os.system("clear")
    PBF(banner,backtomenu)
elif choice == "2" or choice == "02":
    os.system("clear")
    BF(banner,backtomenu)
elif choice == "88":
    os.system("cd .. && rm -rf DORKLIM && git clone https://github.com/Dark-Phinix/DORKLIN && python3 DORKLIN")
elif choice == "99":
    os.system("python3 DORKLIN")
elif choice == "00":
    print("\033[1;33mThanks for using bye bye")
    sys.exit()
else:
    print("Wrong input")
    time.sleep(3)
    os.system("python3 DORKLIN")
